repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
    -   id: trailing-whitespace

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
     -   id: isort
