name: Build executable
run-name: ${{ github.actor }} is running our tests 🚀
on: [push]
jobs:
  Build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [macos-latest, windows-latest]
    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install poetry

      - name: Install Macos Dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          # For Basemap
          brew install geos
          # For Pillow
          #  brew install libtiff libjpeg webp little-cms2
          brew install pillow
          # Update package versions
          poetry lock

      - name: Build Executable
        run: |
          poetry install --without dev --with build --sync
          poetry run pyinstaller --log-level DEBUG RepeatAnalyzer.spec

      - name: Macos debug
        if: matrix.os == 'macos-latest'
        run: |
          ls build
          ls -l /usr/local/lib

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
            name: RepeatAnalyzer
            path: dist/*
