name: Build executable
run-name: ${{ github.actor }} is running our tests 🚀
on: [push]
jobs:
  Build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [macos-latest, windows-latest]
    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -V
          pip install --upgrade pip
          pip install poetry
          pip freeze
          poetry show

      - name: Install Macos Dependencies
        if: matrix.os == 'macos-latest'
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
        run: |
          brew update

          # For Basemap
          brew install geos

          # for pyproj
          pip uninstall -y  pyproj
          brew install proj
          poetry run pip install pyproj --no-binary :all:

          # For Pillow
          pip uninstall -y Pillow
          brew install libjpeg libtiff little-cms2 openjpeg webp
          poetry run pip install Pillow --no-binary :all:

          # For Tkinter
          ls -l /System/Library/Frameworks/Tk.framework/Versions/8.5/
          ls -l /System/Library/Frameworks/Tcl.framework/Versions/8.5/

          # Update package versions
          poetry lock

      - name: Build Executable
        run: |
          pip freeze
          poetry show

          poetry install --without dev --with build --sync
          poetry run pyinstaller --log-level DEBUG RepeatAnalyzer.spec

      - name: Macos debug
        if: matrix.os == 'macos-latest'
        run: |
          ls build/RepeatAnalyzer
          ls -l /usr/local/lib
          ls -l /System/Library/Frameworks/


      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
            name: RepeatAnalyzer
            path: dist/*
