name: GitHub Actions Demo
run-name: ${{ github.actor }} is running our tests 🚀
on: [push]
jobs:
  Unit-Tests:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [macos-latest, windows-latest]
    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install

      - name: Check basemap on macOS
        if: matrix.os == 'macos-latest'
        run: |
          pip wheel --no-cache-dir --use-pep517 "basemap (==1.3.8)"
          poetry search basemap

      - name: Run Unit Tests
        run: |
          poetry run pytest --cov=RepeatAnalyzer tests
