name: GitHub Actions Demo
run-name: ${{ github.actor }} is running our tests 🚀
on: [push]
jobs:
  Unit-Tests:
    runs-on: windows-latest
    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run Unit Tests
        run: |
          poetry run pytest --cov=RepeatAnalyzer tests
          mv .coverage htmlcov

      - name: Upload Coverage Report (Only on Main Branch)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: main-coverage
          path: htmlcov

      - name: Download Main Branch Coverage Artifact
        uses: actions/download-artifact@v2
        id: download_main_coverage
        with:
          name: main-coverage
          path: main-coverage
